name: WODSS
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - flask
  - flask-sqlalchemy
  - flask-script
  - flask-migrate
  - flask-swagger-ui
  - psycopg2
  - requests
  - autopep8
  - ipykernel
  - pandas
  - openpyxl
  - nbconvert
  - lxml
  - xlrd
  - pytest
  - coverage
