"""empty message

Revision ID: 354123dfe85f
Revises: 
Create Date: 2021-03-15 23:43:47.349852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354123dfe85f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidence',
    sa.Column('incidencesId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bfsNr', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('incidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('incidencesId')
    )
    op.create_table('municipality',
    sa.Column('municipalityId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bfsNr', sa.Integer(), nullable=False),
    sa.Column('zipCode', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('canton', sa.String(length=2), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('municipalityId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('municipality')
    op.drop_table('incidence')
    # ### end Alembic commands ###
