"""empty message

Revision ID: 493344eec437
Revises: 
Create Date: 2021-03-29 17:48:57.899356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493344eec437'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipality',
    sa.Column('bfsNr', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('canton', sa.String(length=2), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('bfsNr')
    )
    op.create_table('incidence',
    sa.Column('incidencesId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bfsNr', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('incidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bfsNr'], ['municipality.bfsNr'], ),
    sa.PrimaryKeyConstraint('incidencesId'),
    sa.UniqueConstraint('bfsNr', 'date', name='_bfsNr_date_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidence')
    op.drop_table('municipality')
    # ### end Alembic commands ###
