"""empty message

Revision ID: c68fddeb7c2a
Revises: 493344eec437
Create Date: 2021-04-05 13:01:25.420582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68fddeb7c2a'
down_revision = '493344eec437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidence', sa.Column('cases', sa.Integer(), nullable=False))
    op.add_column('incidence', sa.Column('cases_cumsum_14d', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidence', 'cases_cumsum_14d')
    op.drop_column('incidence', 'cases')
    # ### end Alembic commands ###
