"""empty message

Revision ID: ce3c3d93e12d
Revises: c68fddeb7c2a
Create Date: 2021-04-20 14:55:33.015848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3c3d93e12d'
down_revision = 'c68fddeb7c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidence', 'cases',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidence', 'cases',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
