"""empty message

Revision ID: e4133b475a82
Revises: 354123dfe85f
Create Date: 2021-03-22 17:51:35.021006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4133b475a82'
down_revision = '354123dfe85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('municipality', 'zipCode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('municipality', sa.Column('zipCode', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
